name: Deploy Frontend to Azure Static Web App Locally

on:
  workflow_dispatch:

env:
  APP_LOCATION: "frontend"
  API_LOCATION: ""
  OUTPUT_LOCATION: "build"
  AZURE_STATIC_WEB_APPS_API_TOKEN: "0cbf89858c36f73434d8fe2bcc4bb990bb070201d5613a7989e138dace32425a02-354d32bc-b66a-4406-bd4e-234d3c41c7a801029290e739f010"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ github.token }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}